name: build-and-deply

on: 
  workflow_dispatch:
    inputs:
      env_name:
        type: choice
        required: false
        options:
          - DEV
          - PROD
defaults:
  run:
    shell: powershell

env: 
  DEPLOY_PATH: 'c:/ws/dev'


jobs:
  build_and_deply:
    runs-on: [self-hosted, wr-2012]
    # environment: ${{ github.event.inputs.env_name }}

    steps:
      - name: stop iis server
        run: iisreset /stop      
        
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: build
        run: |
          Remove-Item -Recurse -Force -Path "${{ env.DEPLOY_PATH }}\*"
          Copy-Item -Path './html/index.html' -Destination ${{ env.DEPLOY_PATH }}

      - name: start iis server
        run: iisreset /start

