name: build-and-deply-to-iis

on:
  workflow_dispatch:
    inputs:
      env_name:
        required: true
        type: choice
        options:
          - DEV
          - PROD
          
defaults:
  run:
    shell: powershell

jobs:
  build_and_deply:
    runs-on: [self-hosted, wr-2012]
    environment: ${{ github.event.inputs.env_name }}

    steps:
      - name: stop iis server
        run: iisreset /stop      
        
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: build
        run: |
          Remove-Item -Recurse -Force -Path "${{ secrets.IIS_PATH }}\*"
          Copy-Item -Path './html/index.html' -Destination ${{ secrets.IIS_PATH }}

      - name: start iis server
        run: iisreset /start

